### ISSUE TITLE
系统登录成功后没有任何内容 浏览器试过 safari和chrome

### ISSUE THREAD

**Issue by ericlingmeng** [kkangert/kspider#8]
我没有用容器 而是直接下载的前后端代码本机部署运行 用户账户是手工维护了一个 kspider和 111111到表里面 登录系统时 提示登录成功 但是跳转到系统内没有任何内容 
![1721369759613](https://github.com/user-attachments/assets/58a4a173-5081-4f7b-8de8-6d31300f13d8)

**Comment by kkangert** [comment]
需要复现下

**Comment by kkangert** [comment]
> 我没有用容器 而是直接下载的前后端代码本机部署运行 用户账户是手工维护了一个 kspider和 111111到表里面 登录系统时 提示登录成功 但是跳转到系统内没有任何内容 
> ![1721369759613](https://github.com/user-attachments/assets/58a4a173-5081-4f7b-8de8-6d31300f13d8)
> 

需要复现一下

**Comment by lgs3137** [comment]
![image](https://github.com/user-attachments/assets/7aea146f-f42d-4bcc-ab22-d8dccb0140a2)

```
version: '3'
services:
  kspider-mysql:
    image: mysql:8.0.38
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: kspider-mysql

    # 如需数据持久化更改下方路径
    volumes:
      - ./data/mysql:/var/lib/mysql

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 33060:3306

  # 如需使用selenium节点则开启下方配置
  # https://github.com/SeleniumHQ/docker-selenium
  kspider-selenium:
    image: selenium/standalone-chrome:4.8.1
    container_name: kspider-selenium
    restart: always
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      SE_VNC_PASSWORD: 123456
      SE_NODE_MAX_SESSIONS: 1
      SE_SCREEN_WIDTH: 1920
      SE_SCREEN_HEIGHT: 1080
      SE_SCREEN_DPI: 144

  # https://github.com/kkangert/kspider
  kspider:
    image: kkangert/kspider:latest
    restart: always
    hostname: kspider
    container_name: kspider
    ports:
      - 8086:8086
    depends_on:
      - kspider-mysql
    environment:
      envType: user

  # https://github.com/kkangert/kspider-ui
  kspider-ui:
    image: kkangert/kspider-ui:latest
    restart: always
    hostname: kspider-ui
    container_name: kspider-ui
    ports:
      - 8888:80
    depends_on:
      - kspider
      - kspider-mysql
```
1. 使用最新的v0.0.6本容器化部署也一样的问题。。。
2. 另外MYSQL_ROOT_PASSWORD好像不能改,否则会出现kspider无法连接数据库报错
